### ISSUE TITLE
"Ouvrir le Builder" Button doesn't work — Conflicts with Custom Post Type UI Plugins ?

### ISSUE THREAD

**Issue by vin-san** [Angrycreative/ACF-Page-Builder-Field#5] opened 2016-07-02 21:27 UTC
Hi,

First, thanks for your great work. 👍 

Then, I think I found a bug :
I set up a CPT called 'project' associated with a ACF Page Builder field.
When I create a new 'project', the button "Ouvrir le builder" (excuse my french) doesn't work.
When I apply a ACF Page Builder field to a classic Post, the button "Ouvrir le builder" works.

Apparently, the ACF-Page-Builder-Field plugin doesn't work properly when applied to a CPT created by the Custom Post Type UI Plugins.

Vin

**Comment by pelmered** [comment] 2016-07-03 14:05
Hello, 

Thank you for reporting this. We will investigate. 

We will start by trying to reproduce this error, but before we start we would like some additional information:
Doesn't the page builder button work with any CPTs? Or is it just this one? Or only CPTs created with the `Custom Post Type UI` plugin? Does it work on pages?

**Comment by vin-san** [comment] 2016-07-03 21:17
Hello Peter,

Same results when I tried with a new CTP created with the Custom Post Type UI plugin (I didn’t change the CTP options) : The button doesn’t open the builder.

I only use this particular plugin to create Custom Post Type so I can’t help you with CTPs created by others plugins.

It works with pages : I tested with a home page and a basic page.

Thanks for your fast reply and good luck with that.

Best,

Vincent Moisan

design + code http://vincentmoisan.com/
studio alvin http://studio-alvin.com/

**Comment by vguenichon** [comment] 2016-08-31 12:27
Hi,
I don't use CPT UI but the functions.php file in order to create CPT.
The button doesn't open the builder for me too in CPT and in ACF option page (which is a CPT created by ACF).
And I can confirm that it works with pages.

If it helps.

Valentin GUENICHON

**Comment by pelmered** [comment] 2016-09-21 13:24
Hello, 

Sorry for the late reply here. I totally forgot about this. I think the problem is that Page Builder is not activated for the post types you are adding the page builder button for. You need to activate the page builder under "Settings" -> "Page Builder" for it to load the scripts and work as it should when editing CPTs.

I close this now. Reply if this does not fix the problem.

Regards,
Peter

**Closed as completed by pelmered** 2016-09-21 13:24 UTC
